
version: "3.7"
services:
  6p3-db:
    image: postgres:14.5
    container_name: 6p3-db
    environment:
      - POSTGRES_DB=waunakeeairport
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    volumes:
      - ./.db/:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  django:
    build:
      context: .
      dockerfile: ./Dockerfile-local
    container_name: 6p3
    env_file: .env
    command: python /app/manage.py runserver 0.0.0.0:8000
    depends_on:
      - 6p3-db
      - mailhog
    volumes:
      - .:/app
    ports:
      - 80:8000
      - 8000:8000
    stdin_open: true
    tty: true
  mailhog:
     # image: mailhog/mailhog  # not arm
    image: anatomicjc/mailhog  # is arm64
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui