
version: "3.7"
services:
  6p3-db:
    image: postgres:14.5
    container_name: 6p3-db
    environment:
      - POSTGRES_DB=waunakeeairport
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    expose:
      - 5432
  6p3-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: 6p3-app
    env_file: .env
    depends_on:
      - 6p3-db
    volumes:
      - .:/app
    user: "${USER_RUN}:${GROUP_RUN}"
    ports:
      - "${PORT}:${PORT}"
    stdin_open: true
    tty: true
volumes:
  pg-data: