# Generated by Django 3.2.13 on 2022-05-11 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_alter_taggedpeopleimage_content_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggedpeopleimage',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_people_image', to='timeline.waunakeeimage'),
        ),
    ]
