# Generated by Django 3.2.13 on 2022-05-08 22:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailredirects', '0007_add_autocreate_fields'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeline', '0002_timelineladingpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimelineLadingPage',
            new_name='TimelineLandingPage',
        ),
    ]
