# Generated by Django 3.2.13 on 2022-05-08 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('timeline', '0003_rename_timelineladingpage_timelinelandingpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelinepage',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='timelinepage',
            name='highlight_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
