# Generated by Django 3.2.12 on 2022-04-14 21:53

import localflavor.us.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WAPASignup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=100)),
                ("address1", models.CharField(max_length=250)),
                ("address2", models.CharField(blank=True, max_length=250)),
                ("city", models.CharField(default="Waunakee", max_length=100)),
                ("state", localflavor.us.models.USStateField(default="WI", max_length=2)),
                ("zip_code", models.CharField(default="53597", max_length=20)),
                ("aircraft_year_make_model", models.CharField(blank=True, max_length=100)),
                ("aircraft_n_number", models.CharField(blank=True, max_length=100)),
                ("aircraft_based", models.CharField(blank=True, max_length=100)),
                ("signup_datetime", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-signup_datetime"],
            },
        ),
    ]
