# Generated by Django 3.2.12 on 2022-04-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_runwayuseagreementdocument"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="runwayuseagreementdocument",
            options={"ordering": ["-pk"]},
        ),
        migrations.AddField(
            model_name="runwayuseagreement",
            name="submit_reverse_dns",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
