# Generated by Django 3.2.12 on 2022-04-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_auto_20220415_1542"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runwayuseagreement",
            name="submit_ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
