# Generated by Django 3.2.12 on 2022-04-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_alter_runwayuseagreement_submit_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="runwayuseagreement",
            name="s3_pdf_filename",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="runwayuseagreement",
            name="sns_message_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="runwayuseagreement",
            name="sns_processed_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="runwayuseagreement",
            name="sns_queued_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
