# Generated by Django 3.2.13 on 2022-08-15 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20220415_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runwayuseagreement',
            name='certificate_number',
        ),
    ]
