# Generated by Django 3.2.19 on 2023-05-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_remove_runwayuseagreement_certificate_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AOASubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('purpose', models.TextField()),
                ('submit_datetime', models.DateTimeField(auto_now_add=True)),
                ('sns_processed_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
