# Generated by Django 4.2.7 on 2023-11-24 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_aoasubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AOASubmission',
        ),
    ]
