# Generated by Django 4.2.7 on 2023-11-24 05:41

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='cards',
            field=wagtail.fields.StreamField([('card', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(max_length=120)), ('blurb', wagtail.blocks.RichTextBlock()), ('button', wagtail.blocks.CharBlock(max_length=120)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('page', wagtail.blocks.PageChooserBlock())]))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='pilotairportinfopage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], use_json_field=True),
        ),
    ]
